# Generated by Django 3.2.7 on 2023-07-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenciaApp', '0003_auto_20230725_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorias',
            name='descripción',
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=100),
        ),
    ]
