# Generated by Django 3.2.7 on 2023-07-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenciaApp', '0004_auto_20230726_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorias',
            name='nombreCategoria',
        ),
    ]
