from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .CategoriasView import CategoriasView
from .CategoriaView2 import Categorias
from .ProductosView import ProductosView
from .templates import views
from .loginView import CustomTokenObtainPairView
from .SubcategoriasView import SubcategoriasView
from .ProductosView2 import Productos
from .SubcategoriasView2 import Subcategorias