from agenciaApp.serializers.userSerializer import UserSerializer
from agenciaApp.serializers.CategoriasSerializer import Categorias
from agenciaApp.serializers.subcategoriasSerializer import Subcategorias
from agenciaApp.serializers.ProductosSerializer import Productos